name: senai_f1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0-216.1.beta


dependencies:
  flutter:
    sdk: flutter
    

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  firebase_auth: ^5.4.0
  provider: ^6.1.2
  mask_text_input_formatter: ^2.9.0
  awesome_dialog: ^3.2.1
  firebase_database: ^11.3.0
  cloud_firestore: ^5.6.1
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.1
  flutter_native_splash: ^2.4.4
  
  

  firebase_core: any
  fl_chart: ^0.70.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  remove_alpha_ios: true
  android: true
  ios: true
  image_path: "assets/logo_foreground.png"
  adaptative_icon_foreground: "assets/logo_foreground.png"
  adaptative_icon_background: "#ff0033"

# flutter_native_splash:
#   color: "000000"
#   image: assets/splash.png
#   android: true
#   ios: true

flutter:
  uses-material-design: true

  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
   

  #   - images/a_dot_ham.jpeg

 
  fonts:
    - family: LeagueGothic
      fonts:
        - asset: assets/fonts/LeagueGothic-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: DS-Digital
      fonts:
        - asset: assets/fonts/DS-DIGI.ttf
  

